export default {
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNOUT_USER: 'SIGNOUT_USER',
  SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
  RESTORE_TOKEN: 'RESTORE_TOKEN',
  RESTORE_TOKEN_SUCCESS: 'RESTORE_TOKEN_SUCCESS',
};
