export default {
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNOUT_USER: 'SIGNOUT_USER',
  SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
  RESTORE_TOKEN: 'RESTORE_TOKEN',
  RESTORE_TOKEN_SUCCESS: 'RESTORE_TOKEN_SUCCESS',
  ADD_ORDER: 'ADD_ORDER',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  SET_CURRORDER: 'SET_CURRORDER',
  SET_CURRORDER_SUCCESS: 'SET_CURRORDER_SUCCESS',
};
